version: "3"
services:
  iptv-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: wget --no-verbose --tries=1 --spider https://1.1.1.1 || exit 1
      interval: 5m # Default: 30s
      timeout: 15s # Default: 30s
      retries: 1 # Default: 3
      start_period: 5s # Default: 0s
      start_interval: 10s # Default: 5s
    volumes:
      # If your are using local m3u file instead of m3u remote file
      # put your m3u file in this folder
      - ./iptv:/root/iptv
    container_name: "iptv-proxy"
    restart: on-failure
    ports:
       # have to be the same as ENV variable PORT
      - 8080:8080
    environment:
      # if you are using m3u remote file
      # M3U_URL: https://example.com/iptvfile.m3u
      M3U_URL: http://premiumeclipse2.xyz/get.php?username=SimonH170724&password=beWDwym&type=m3u_plus&output=ts
      # Port to expose the IPTVs endpoints
      PORT: 8080
      # Hostname or IP to expose the IPTVs endpoints (for machine not for docker)
      HOSTNAME: https://p01--iptv-proxy--4mw9zxvhkfnz.code.run
      GIN_MODE: release
      ## Xtream-code proxy configuration
      XTREAM_USER: SimonH170724
      XTREAM_PASSWORD: beWDwym
      XTREAM_BASE_URL: http://premiumeclipse2.xyz/get.php?username=SimonH170724&password=beWDwym&type=m3u_plus&output=ts
      ##### UNSAFE AUTH TODO ADD REAL AUTH
      #will be used for m3u and xtream auth poxy
      USER: windza
      PASSWORD: windza
      # ---- Additional debugging options ----
      #DEBUG_LOGGING: true
      # Save the IPTV Provider responses to this location
      #CACHE_FOLDER: /root/iptv/cache/
      # Default to using Advanced parsing. Disable it with:
      #USE_XTREAM_LEGACY_PARSING: true
      # ERROR_DETAIL_LEVEL values: none, simple (default), full
      #ERROR_DETAIL_LEVEL: simple
